ingress:
    hosts:
    - host: rasax-gpmt.westeurope.cloudapp.azure.com
      paths:
      - /
    
    tls:
    - secretName: rasa-x-tls
      hosts:
      - rasax-gpmt.westeurope.cloudapp.azure.com

    annotations:
        kubernetes.io/ingress.class: nginx 
        cert-manager.io/issuer: letsencrypt
rasax:
    persistence:
        size: "8Gi"
    
postgresql:
    persistence:
        size: "8Gi"

