version: "3"

services:
    rasa:
        build:
            dockerfile: Dockerfile
            context: ./
        networks:
            - gpmt-default
        ports:
            - "5005:5005"
    duckling:
        image: rasa/duckling:latest
        networks:
            - gpmt-default
        ports:
            - "8000:8000"
    app:
        build:
            dockerfile: Dockerfile
            context: ./actions
        networks:
            - gpmt-default
        ports:
            - "5055:5055"
        environment:
            - MONGO_URL=mongodb://gpmt-mongo:27017

networks:
    gpmt-default:
        name: gpmt-default