defaultBackend:
    nodeSelector:
        beta.kubernetes.io/os: linux

controller:
    replicaCount: 1
    nodeSelector:
        beta.kubernetes.io/os: linux
    
    admissionWebhooks:
        patch:
            nodeSelector:
                beta.kubernetes.io/os: linux

    service:
        # aquired through azure public ip service
        loadBalancerIP: "20.105.182.1"
        annotations:
            service.beta.kubernetes.io/azure-dns-label-name: "rasax-gpmt"

