rasax:
    initialUser:
        username: "gpmt"
        password: "gympap?password"

rasa:
    version: "2.3.0"

    additionalChannelCredentials:
        rest:

app:
    name: "hakrac/gpmt-rasa"
    # name: "gpmtregistry.azurecr.io/gpmt-rasa-actions"
    tag: "latest"

nginx:
    enabled: false

