ingress:
    hosts:
    - host: rasax-gpmt.westeurope.cloudapp.azure.com
      paths:
      - /
    - host: rasa.gympapmt.de
      paths:
      - /
    
    tls:
    - secretName: rasa-x-tls
      hosts:
      - rasax-gpmt.westeurope.cloudapp.azure.com
      - rasa.gympapmt.de

    annotations:
        kubernetes.io/ingress.class: nginx 
        cert-manager.io/issuer: letsencrypt

app:
    name: "gpmtcontainerregistry.azurecr.io/gpmt-rasa-actions"
    tag: "latest"
    extraEnvs:
    - name: "MONGO_URL"
      valueFrom:
        secretKeyRef:
           name: cosmosdb
           key: url

rasax:
    initialUser:
        username: "gpmt"
        password: "gympap?password"
    persistence:
        size: "8Gi"
    
postgresql:
    persistence:
        size: "8Gi"

rasa:
    version: "2.8.0"
    additionalChannelCredentials:
        rest:
    versions:
      rasaWorkers:
          resources:
              requests:
                  memory: "1Gi"

nginx:
    enabled: false
