ingress:
    hosts:
    - host: rasa.gympapmt.de
      paths:
      - /
    
    tls:
    - secretName: rasa-x-tls
      hosts:    
      - rasa.gympapmt.de

    annotations:
        kubernetes.io/ingress.class: nginx 
        cert-manager.io/issuer: letsencrypt

app:
    name: "gpmtcontainerregistry.azurecr.io/gpmt-rasa-actions"
    tag: "latest"
    extraEnvs:
    - name: "MONGO_URL"
      valueFrom:
        secretKeyRef:
          name: cosmosdb
          key: url

rasax:
    initialUser:
        username: "gpmt"
        password: "gympap?password"
    tag: "0.40.0"

rasa:
    version: "2.6.0"
    additionalChannelCredentials:
        rest:

nginx:
    enabled: false
