rasax:
    initialUser:
        username: "gpmt"
        password: "gympap?password"

rasa:
    version: "2.6.0"
    name: "hakrac/gpmt-rasa"
    tag: "latest"

    additionalChannelCredentials:
        # rest:
        channels.redis.RedisInputChannel:

app:
    name: "hakrac/gpmt-rasa-actions"
    # name: "gpmtregistry.azurecr.io/gpmt-rasa-actions"
    tag: "latest"

nginx:
    enabled: false

