rasax:
    initialUser:
        username: "gpmt"
        password: "gympap?password"

rasa:
    version: "2.3.0"

    additionalChannelCredentials:
        rest:

app:
    name: "gpmtregistry.azurecr.io/gpmt-rasa-actions"
    tag: "v1"

nginx:
    enabled: false



