on:
  push:
    branches: [ master ]

name: Test rasa

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
    - name: ACR login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: docker pull gpmtcontainerregistry.azurecr.io/gpmt-rasa-actions:latest
    - name: Run `rasa`
      run: docker-compose -f docker-compose.yml up
