on:
  push:
    branches: [ master ]

name: Test rasa

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v2
    - name: ACR login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        mkdir nginx-config-files && \
        wget -qO nginx-config-files/nginx.conf https://storage.googleapis.com/rasa-x-releases/0.42.0/nginx-config-files/nginx.conf && \
        wget -qO nginx-config-files/ssl.conf.template https://storage.googleapis.com/rasa-x-releases/0.42.0/nginx-config-files/ssl.conf.template && \
        wget -qO nginx-config-files/rasax.nginx.template https://storage.googleapis.com/rasa-x-releases/0.42.0/nginx-config-files/rasax.nginx.template && \
    - name: Run `rasa`
      run: docker-compose -f docker-compose.yml up
